---
- name: Install tmux on Debian/Ubuntu
  apt:
    name: tmux
    state: present
  when: ansible_os_family == "Debian"

- name: Install tmux on macOS
  homebrew:
    name: tmux
    state: present
  when: ansible_os_family == "Darwin"

- name: Clone or Update TPM
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    update: yes

- name: Stow tmux configuation
  command: stow tmux
  args:
    chdir: ~/.dotfiles

- name: Install plugins
  command: ~/.tmux/plugins/tpm/bin/install_plugins
  ignore_errors: yes


