---
- name: Clone Neovim repository
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: '/usr/local/src/neovim'
    version: 'master'  # You can specify a tag or branch if needed
    update: yes

- name: Build Neovim
  command: >
    make CMAKE_BUILD_TYPE=Release
  args:
    chdir: '/usr/local/src/neovim'
  when: ansible_os_family == "Debian"

- name: Install Neovim
  command: >
    make install
  args:
    chdir: '/usr/local/src/neovim'
  when: ansible_os_family == "Debian"

- name: Create symlink for nvim
  command: "ln -s /usr/local/bin/nvim /usr/bin/nvim"
  args:
    removes: /usr/bin/nvim  # Only create the symlink if it doesn't already exist

- name: Stow neovim configuation
  command: stow nvim
  args:
    chdir: ~/.dotfiles
